version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_atividadesbd
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: atividade_db
    volumes:
      - ./tarefa02-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5051:5432"
    networks:
      - atividadesbd_network

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: pgadmin_atividadesbd
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - atividadesbd_network
    depends_on:
      - postgres

networks:
  atividadesbd_network:
    driver: bridge
